name: CMake

on:
  push

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: run-vcpkg
      uses: lukka/run-vcpkg@v10.7
      with:
        vcpkgGitCommitId: 6f7ffeb18f99796233b958aaaf14ec7bd4fb64b2

    - name: Configure CMake
      run: vcpkg install opengl 

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
